### ISSUE TITLE
How does ZAP deal with "skipped tests"?

### ISSUE THREAD

**Issue by hansott** [zaptst/zap#4]
PHPUnit always you to skip certain tests depending on the used OS, available PHP extensions, ...

Docs: https://phpunit.readthedocs.io/en/7.1/incomplete-and-skipped-tests.html#skipping-tests

I know that tests like that are probably not a good idea and each test should always be able to run. It's a feature that's used though. I'm wondering whether these skipped tests should be supported by ZAP... What do you think?

**Comment by mjarkk** [comment]
A skipped test is also handy when you know a test will fail because of a change you want.  
Because of that it might be handy to tell a user that tests are being skipped so they don't forget to fix those tests  
  
Ava tells you in the output when tests are skipped: https://github.com/avajs/ava#skipping-tests  
I'm not sure if other test frameworks do the same thing with skipped tests  
  
Myabe add something like this
```json
{
	"skipped": true
}
```

**Comment by jamiebuilds** [comment]
There's already a `"skipped"` event, does that work well enough?

**Comment by hansott** [comment]
Sorry @jamiebuilds, I must have missed that when reading the spec... I'm going to close this!

I'm going to try implementing a PHPUnit ZAP extension for fun. 😬
